name: snowflake-migration-demo

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: List files in workspace
        run: ls -l $GITHUB_WORKSPACE

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          pip install schemachange
          schemachange -f $GITHUB_WORKSPACE/deploy \
            -a $SF_ACCOUNT \
            -u $SF_USERNAME \
            -p $SF_PASSWORD \
            -r $SF_ROLE \
            -w $SF_WAREHOUSE \
            -d $SF_DATABASE \
            -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table
            --config-file-name connections.toml \
            --connection-name snowflake_dev \
            -c ${{ secrets.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table
