name: snowflake-migration-demo

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: List files in workspace
        run: ls -l $GITHUB_WORKSPACE

      - name: Create connections.toml
        run: |
          cat > $GITHUB_WORKSPACE/connections.toml << EOF
          [snowflake_dev]
          account = "${{ secrets.SF_ACCOUNT }}"
          user = "${{ secrets.SF_USERNAME }}"
          password = "${{ secrets.SF_PASSWORD }}"
          role = "${{ secrets.SF_ROLE }}"
          warehouse = "${{ secrets.SF_WAREHOUSE }}"
          database = "${{ secrets.SF_DATABASE }}"
          EOF
          
      - name: Run schemachange
        run: |
          pip install schemachange
          echo "Checking config folder contents:"
          ls -la $GITHUB_WORKSPACE
          cat $GITHUB_WORKSPACE/connections.toml
          schemachange -f $GITHUB_WORKSPACE/deploy \
            --config-folder $GITHUB_WORKSPACE \
            --config-file-name connections.toml \
            --connection-name snowflake_dev \
            -c ${{ secrets.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table
